### ISSUE TITLE
The error I'm getting using the bert method

### ISSUE THREAD

**Issue by dengjinyu123** [nilmtk/nilmtk-contrib#65]
Has anyone encountered the following error?
2022-03-03 23:42:05.100902: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Using TensorFlow backend.
2022-03-03 23:42:08.117155: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2022-03-03 23:42:08.130097: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2022-03-03 23:42:08.133384: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-NU98JL3
2022-03-03 23:42:08.133667: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-NU98JL3
Traceback (most recent call last):
  File "D:/代码/nilmtk-contrib-master/sample_notebooks/NILMTK API.py", line 5, in <module>
    from nilmtk_contrib.disaggregate import DAE,Seq2Point, Seq2Seq, RNN, WindowGRU,bert
  File "D:\代码\nilmtk-contrib-master\nilmtk_contrib\__init__.py", line 1, in <module>
    from . import disaggregate
  File "D:\代码\nilmtk-contrib-master\nilmtk_contrib\disaggregate\__init__.py", line 14, in <module>
    from .bert import BERT
  File "D:\代码\nilmtk-contrib-master\nilmtk_contrib\disaggregate\bert.py", line 15, in <module>
    from keras.layers import Layer,MultiHeadAttention,LayerNormalization,Embedding
ImportError: cannot import name 'MultiHeadAttention' from 'keras.layers' (D:\ANACONDA3\envs\nilm\lib\site-packages\keras\layers\__init__.py)
Closing remaining open files:C:\Users\DJY\AppData\Local\Temp\nilmtk-i7g167np.h5...done

**Comment by nipunbatra** [comment]
Requesting @hetvishastri to look into this.

**Comment by paulfrank1997** [comment]
Can I ask you about what version of tensorflow, h5py and keras you install? The original nilmtk-contrib does not contain tensorflow. But after I tried to install it by myself, I still got errors. So I was wondering whether that was caused by version problems.

**Comment by Rohitkr1997** [comment]
Hey can anyone using BERT send the enivronment .yml file so that others can use it. There always seems to be conficts in the anaconda environment when getting bert to work.
